"""crudddddddd

Revision ID: 396e7025042e
Revises: 
Create Date: 2024-11-19 18:48:30.692861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396e7025042e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adversario', sa.String(length=100), nullable=True),
    sa.Column('data', sa.String(length=50), nullable=True),
    sa.Column('id_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_time'], ['time.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogo')
    op.drop_table('time')
    # ### end Alembic commands ###
